### ISSUE TITLE
file exclusions

### ISSUE THREAD

**Issue by naseemkullah** [ActionsDesk/lfs-warning#125]
Hello @ppremk, would you be on board with adding an option to exclude certain files/file extensions from the large file check?

e.g. only want to warn on miniified `js` or large `json` files, but not xcode `project.pbxproj` files

**Comment by ppremk** [comment]
hi @naseemkullah 👋🏽 
What would be the use case? I am thinking along the lines where git tracks content and the size of the blob is what we are comparing against.. How would the logic change here? 🙂 Asking to better understand the implementation.

**Comment by brenmcnamara** [comment]
hi @ppremk ,

Thanks so much for the quick response and taking a look 🙂

I work with @naseemkullah and we raised this issue today. The use case we have is:

1. We would like to prevent large file blobs from getting into our repo and warn against that
2. We have one particular exception to this rule, which is Xcode's `project.pbxproj` file

This is a text file that Xcode maintains for all iOS projects. It contains all the compiler information (header search paths, dependencies, list of source file dependencies, compiler flags and configurations, and device metadata) and frequently changes when an iOS developer makes changes to the iOS project (anything from modifying compiler flags, adding third-party dependencies,  and even just creating a new `swift` file in the project). Naturally, this file becomes massive for any medium sized app because of the all the things it is tracking.

We need to frequently go through the process of checking this file in and resolving merge conflicts (sometimes manually). If we check this into LFS, we lose the ability to do so. This means engineers will frequently be merging broken iOS commits, so it's important we track this file using version control. This file is a one-off exception to our rule about large file sizes.

**Comment by ppremk** [comment]
@brenmcnamara thank you for the explanation, it is clear, we could add an input to collect a list of exception of files or its extension as suggested by @naseemkullah .. I am thinking along the line of:

```yml
excludefile:  # file name or extension 
    description: 'file to be excluded from the check'
    required: false
    default: '.pbxproj' 
```

would that work for you folks? 🙂

**Comment by brenmcnamara** [comment]
Looks good to me! @naseemkullah ?

**Comment by naseemkullah** [comment]
sounds great! 🙏 

one thing is I think the input should be a list of glob patterns to match files for maximum flexibility, we could use https://github.com/sindresorhus/globby or similar. if passing in extension/filename directly we might hit some edge cases, such as a very large dotfile
